# https://taskfile.dev

version: "3"

tasks:
  default:
    - task --list-all

  lint:
    - go run github.com/nishanths/exhaustive/cmd/exhaustive@latest -default-signifies-exhaustive ./...
    - go run honnef.co/go/tools/cmd/staticcheck@latest ./...
    - go vet ./...

  release:
    deps: [tidy, lint, test, fmt]
    cmds:
      - go build -tags="release"

  tidy:
    - go mod tidy -v

  update-deps:
    cmds:
      - go get -u
      - go clean -modcache
      - task tidy

  test:
    - go test -v -run '^((?!TestGuestbookBasicFlow).)*$' -timeout 30s ./... 2>&1 | cat

  test-all:
    - go test -v -timeout 3m ./... 2>&1 | cat

  test-e2e:
    desc: Run end-to-end browser tests (includes auth flows)
    cmds:
      - go test -v -run TestGuestbookBasicFlow -timeout 3m 2>&1 | cat

  test-api:
    desc: Run API caching tests only
    cmds:
      - go test -v -run TestAPIEndpointsCaching -timeout 30s 2>&1 | cat

  run:
    - go run .

  dev:
    - air -c .air.toml

  fmt:
    - go fmt ./...
